// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RIK_Proovitöö.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240229140544_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RIK_Proovitöö.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompanyAttendeeAmount")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExtraInfo")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<long>("RegistryCode")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyAttendeeAmount = 18,
                            CompanyName = "Company 1",
                            ExtraInfo = "Test extra info 1",
                            PaymentType = 1,
                            RegistryCode = 77076728913L
                        },
                        new
                        {
                            ID = 2,
                            CompanyAttendeeAmount = 15,
                            CompanyName = "Company 2",
                            ExtraInfo = "Test extra info 2",
                            PaymentType = 0,
                            RegistryCode = 58523279186L
                        },
                        new
                        {
                            ID = 3,
                            CompanyAttendeeAmount = 3,
                            CompanyName = "Company 3",
                            ExtraInfo = "Test extra info 3",
                            PaymentType = 1,
                            RegistryCode = 11643847822L
                        },
                        new
                        {
                            ID = 4,
                            CompanyAttendeeAmount = 17,
                            CompanyName = "Company 4",
                            ExtraInfo = "Test extra info 4",
                            PaymentType = 1,
                            RegistryCode = 45937465593L
                        },
                        new
                        {
                            ID = 5,
                            CompanyAttendeeAmount = 56,
                            CompanyName = "Company 5",
                            ExtraInfo = "Test extra info 5",
                            PaymentType = 1,
                            RegistryCode = 37007095639L
                        },
                        new
                        {
                            ID = 6,
                            CompanyAttendeeAmount = 37,
                            CompanyName = "Company 6",
                            ExtraInfo = "Test extra info 6",
                            PaymentType = 1,
                            RegistryCode = 59874230416L
                        },
                        new
                        {
                            ID = 7,
                            CompanyAttendeeAmount = 11,
                            CompanyName = "Company 7",
                            ExtraInfo = "Test extra info 7",
                            PaymentType = 0,
                            RegistryCode = 71885517835L
                        },
                        new
                        {
                            ID = 8,
                            CompanyAttendeeAmount = 85,
                            CompanyName = "Company 8",
                            ExtraInfo = "Test extra info 8",
                            PaymentType = 0,
                            RegistryCode = 43484919238L
                        },
                        new
                        {
                            ID = 9,
                            CompanyAttendeeAmount = 19,
                            CompanyName = "Company 9",
                            ExtraInfo = "Test extra info 9",
                            PaymentType = 1,
                            RegistryCode = 7246784685L
                        },
                        new
                        {
                            ID = 10,
                            CompanyAttendeeAmount = 51,
                            CompanyName = "Company 10",
                            ExtraInfo = "Test extra info 10",
                            PaymentType = 0,
                            RegistryCode = 48937849655L
                        });
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2024, 10, 5, 16, 5, 43, 731, DateTimeKind.Local).AddTicks(9672),
                            Location = "Location1",
                            Name = "Event1"
                        },
                        new
                        {
                            ID = 2,
                            Date = new DateTime(2024, 4, 15, 16, 5, 43, 731, DateTimeKind.Local).AddTicks(9713),
                            Location = "Location2",
                            Name = "Event2"
                        },
                        new
                        {
                            ID = 3,
                            Date = new DateTime(2023, 8, 1, 16, 5, 43, 731, DateTimeKind.Local).AddTicks(9716),
                            Location = "Location3",
                            Name = "Event3"
                        },
                        new
                        {
                            ID = 4,
                            Date = new DateTime(2024, 3, 25, 16, 5, 43, 731, DateTimeKind.Local).AddTicks(9718),
                            Location = "Location4",
                            Name = "Event4"
                        },
                        new
                        {
                            ID = 5,
                            Date = new DateTime(2023, 7, 31, 16, 5, 43, 731, DateTimeKind.Local).AddTicks(9720),
                            Location = "Location5",
                            Name = "Event5"
                        },
                        new
                        {
                            ID = 6,
                            Date = new DateTime(2024, 6, 17, 16, 5, 43, 731, DateTimeKind.Local).AddTicks(9723),
                            Location = "Location6",
                            Name = "Event6"
                        },
                        new
                        {
                            ID = 7,
                            Date = new DateTime(2023, 11, 19, 16, 5, 43, 731, DateTimeKind.Local).AddTicks(9725),
                            Location = "Location7",
                            Name = "Event7"
                        },
                        new
                        {
                            ID = 8,
                            Date = new DateTime(2023, 3, 15, 16, 5, 43, 731, DateTimeKind.Local).AddTicks(9727),
                            Location = "Location8",
                            Name = "Event8"
                        },
                        new
                        {
                            ID = 9,
                            Date = new DateTime(2023, 9, 10, 16, 5, 43, 731, DateTimeKind.Local).AddTicks(9729),
                            Location = "Location9",
                            Name = "Event9"
                        },
                        new
                        {
                            ID = 10,
                            Date = new DateTime(2023, 4, 27, 16, 5, 43, 731, DateTimeKind.Local).AddTicks(9732),
                            Location = "Location10",
                            Name = "Event10"
                        });
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.EventCompany", b =>
                {
                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.HasKey("EventID", "CompanyID");

                    b.HasIndex("CompanyID");

                    b.ToTable("EventCompanies");

                    b.HasData(
                        new
                        {
                            EventID = 1,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 10
                        });
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.EventIndividual", b =>
                {
                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<int>("IndividualID")
                        .HasColumnType("int");

                    b.HasKey("EventID", "IndividualID");

                    b.HasIndex("IndividualID");

                    b.ToTable("EventIndividuals");

                    b.HasData(
                        new
                        {
                            EventID = 1,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 10
                        });
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.Individual", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ExtraInfo")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<long>("PersonalCode")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Individuals");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ExtraInfo = "Test extra info 1",
                            FirstName = "First1",
                            LastName = "Last1",
                            PaymentType = 0,
                            PersonalCode = 24685364055L
                        },
                        new
                        {
                            ID = 2,
                            ExtraInfo = "Test extra info 2",
                            FirstName = "First2",
                            LastName = "Last2",
                            PaymentType = 1,
                            PersonalCode = 3874062183L
                        },
                        new
                        {
                            ID = 3,
                            ExtraInfo = "Test extra info 3",
                            FirstName = "First3",
                            LastName = "Last3",
                            PaymentType = 0,
                            PersonalCode = 69375682923L
                        },
                        new
                        {
                            ID = 4,
                            ExtraInfo = "Test extra info 4",
                            FirstName = "First4",
                            LastName = "Last4",
                            PaymentType = 0,
                            PersonalCode = 62095199808L
                        },
                        new
                        {
                            ID = 5,
                            ExtraInfo = "Test extra info 5",
                            FirstName = "First5",
                            LastName = "Last5",
                            PaymentType = 0,
                            PersonalCode = 8756475892L
                        },
                        new
                        {
                            ID = 6,
                            ExtraInfo = "Test extra info 6",
                            FirstName = "First6",
                            LastName = "Last6",
                            PaymentType = 0,
                            PersonalCode = 24004688340L
                        },
                        new
                        {
                            ID = 7,
                            ExtraInfo = "Test extra info 7",
                            FirstName = "First7",
                            LastName = "Last7",
                            PaymentType = 0,
                            PersonalCode = 29193954685L
                        },
                        new
                        {
                            ID = 8,
                            ExtraInfo = "Test extra info 8",
                            FirstName = "First8",
                            LastName = "Last8",
                            PaymentType = 1,
                            PersonalCode = 22816975534L
                        },
                        new
                        {
                            ID = 9,
                            ExtraInfo = "Test extra info 9",
                            FirstName = "First9",
                            LastName = "Last9",
                            PaymentType = 1,
                            PersonalCode = 60117461554L
                        },
                        new
                        {
                            ID = 10,
                            ExtraInfo = "Test extra info 10",
                            FirstName = "First10",
                            LastName = "Last10",
                            PaymentType = 0,
                            PersonalCode = 95323698590L
                        });
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.EventCompany", b =>
                {
                    b.HasOne("RIK_Proovitöö.Models.Company", "Company")
                        .WithMany("EventCompanies")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIK_Proovitöö.Models.Event", "Event")
                        .WithMany("EventCompanies")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.EventIndividual", b =>
                {
                    b.HasOne("RIK_Proovitöö.Models.Event", "Event")
                        .WithMany("EventIndividuals")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIK_Proovitöö.Models.Individual", "Individual")
                        .WithMany("EventIndividuals")
                        .HasForeignKey("IndividualID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.Company", b =>
                {
                    b.Navigation("EventCompanies");
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.Event", b =>
                {
                    b.Navigation("EventCompanies");

                    b.Navigation("EventIndividuals");
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.Individual", b =>
                {
                    b.Navigation("EventIndividuals");
                });
#pragma warning restore 612, 618
        }
    }
}
