// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RIK_Proovitöö.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240229154116_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RIK_Proovitöö.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompanyAttendeeAmount")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExtraInfo")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<long>("RegistryCode")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyAttendeeAmount = 43,
                            CompanyName = "Company 1",
                            ExtraInfo = "Test extra info 1",
                            PaymentType = 1,
                            RegistryCode = 77123954950L
                        },
                        new
                        {
                            ID = 2,
                            CompanyAttendeeAmount = 31,
                            CompanyName = "Company 2",
                            ExtraInfo = "Test extra info 2",
                            PaymentType = 0,
                            RegistryCode = 87565072526L
                        },
                        new
                        {
                            ID = 3,
                            CompanyAttendeeAmount = 86,
                            CompanyName = "Company 3",
                            ExtraInfo = "Test extra info 3",
                            PaymentType = 1,
                            RegistryCode = 41433813380L
                        },
                        new
                        {
                            ID = 4,
                            CompanyAttendeeAmount = 15,
                            CompanyName = "Company 4",
                            ExtraInfo = "Test extra info 4",
                            PaymentType = 1,
                            RegistryCode = 42176155251L
                        },
                        new
                        {
                            ID = 5,
                            CompanyAttendeeAmount = 80,
                            CompanyName = "Company 5",
                            ExtraInfo = "Test extra info 5",
                            PaymentType = 0,
                            RegistryCode = 56112707159L
                        },
                        new
                        {
                            ID = 6,
                            CompanyAttendeeAmount = 52,
                            CompanyName = "Company 6",
                            ExtraInfo = "Test extra info 6",
                            PaymentType = 1,
                            RegistryCode = 15954689450L
                        },
                        new
                        {
                            ID = 7,
                            CompanyAttendeeAmount = 41,
                            CompanyName = "Company 7",
                            ExtraInfo = "Test extra info 7",
                            PaymentType = 1,
                            RegistryCode = 39810279648L
                        },
                        new
                        {
                            ID = 8,
                            CompanyAttendeeAmount = 77,
                            CompanyName = "Company 8",
                            ExtraInfo = "Test extra info 8",
                            PaymentType = 1,
                            RegistryCode = 19969956326L
                        },
                        new
                        {
                            ID = 9,
                            CompanyAttendeeAmount = 60,
                            CompanyName = "Company 9",
                            ExtraInfo = "Test extra info 9",
                            PaymentType = 1,
                            RegistryCode = 2935804317L
                        },
                        new
                        {
                            ID = 10,
                            CompanyAttendeeAmount = 25,
                            CompanyName = "Company 10",
                            ExtraInfo = "Test extra info 10",
                            PaymentType = 1,
                            RegistryCode = 25433291606L
                        });
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2023, 12, 2, 17, 41, 16, 66, DateTimeKind.Local).AddTicks(4280),
                            Location = "Location1",
                            Name = "Event1"
                        },
                        new
                        {
                            ID = 2,
                            Date = new DateTime(2023, 8, 14, 17, 41, 16, 66, DateTimeKind.Local).AddTicks(4320),
                            Location = "Location2",
                            Name = "Event2"
                        },
                        new
                        {
                            ID = 3,
                            Date = new DateTime(2024, 5, 17, 17, 41, 16, 66, DateTimeKind.Local).AddTicks(4322),
                            Location = "Location3",
                            Name = "Event3"
                        },
                        new
                        {
                            ID = 4,
                            Date = new DateTime(2024, 1, 20, 17, 41, 16, 66, DateTimeKind.Local).AddTicks(4325),
                            Location = "Location4",
                            Name = "Event4"
                        },
                        new
                        {
                            ID = 5,
                            Date = new DateTime(2024, 3, 8, 17, 41, 16, 66, DateTimeKind.Local).AddTicks(4327),
                            Location = "Location5",
                            Name = "Event5"
                        },
                        new
                        {
                            ID = 6,
                            Date = new DateTime(2024, 9, 6, 17, 41, 16, 66, DateTimeKind.Local).AddTicks(4330),
                            Location = "Location6",
                            Name = "Event6"
                        },
                        new
                        {
                            ID = 7,
                            Date = new DateTime(2023, 7, 10, 17, 41, 16, 66, DateTimeKind.Local).AddTicks(4332),
                            Location = "Location7",
                            Name = "Event7"
                        },
                        new
                        {
                            ID = 8,
                            Date = new DateTime(2024, 12, 31, 17, 41, 16, 66, DateTimeKind.Local).AddTicks(4354),
                            Location = "Location8",
                            Name = "Event8"
                        },
                        new
                        {
                            ID = 9,
                            Date = new DateTime(2024, 7, 17, 17, 41, 16, 66, DateTimeKind.Local).AddTicks(4356),
                            Location = "Location9",
                            Name = "Event9"
                        },
                        new
                        {
                            ID = 10,
                            Date = new DateTime(2024, 10, 2, 17, 41, 16, 66, DateTimeKind.Local).AddTicks(4360),
                            Location = "Location10",
                            Name = "Event10"
                        });
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.EventCompany", b =>
                {
                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.HasKey("EventID", "CompanyID");

                    b.HasIndex("CompanyID");

                    b.ToTable("EventCompanies");

                    b.HasData(
                        new
                        {
                            EventID = 1,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 1,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 2,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 3,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 4,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 5,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 6,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 7,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 8,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 9,
                            CompanyID = 10
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 1
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 2
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 3
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 4
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 5
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 6
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 7
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 8
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 9
                        },
                        new
                        {
                            EventID = 10,
                            CompanyID = 10
                        });
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.EventIndividual", b =>
                {
                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<int>("IndividualID")
                        .HasColumnType("int");

                    b.HasKey("EventID", "IndividualID");

                    b.HasIndex("IndividualID");

                    b.ToTable("EventIndividuals");

                    b.HasData(
                        new
                        {
                            EventID = 1,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 1,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 2,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 3,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 4,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 5,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 6,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 7,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 8,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 9,
                            IndividualID = 10
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 1
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 2
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 3
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 4
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 5
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 6
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 7
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 8
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 9
                        },
                        new
                        {
                            EventID = 10,
                            IndividualID = 10
                        });
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.Individual", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ExtraInfo")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<long>("PersonalCode")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Individuals");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ExtraInfo = "Test extra info 1",
                            FirstName = "First1",
                            LastName = "Last1",
                            PaymentType = 0,
                            PersonalCode = 46002710232L
                        },
                        new
                        {
                            ID = 2,
                            ExtraInfo = "Test extra info 2",
                            FirstName = "First2",
                            LastName = "Last2",
                            PaymentType = 1,
                            PersonalCode = 12416994081L
                        },
                        new
                        {
                            ID = 3,
                            ExtraInfo = "Test extra info 3",
                            FirstName = "First3",
                            LastName = "Last3",
                            PaymentType = 0,
                            PersonalCode = 61938462307L
                        },
                        new
                        {
                            ID = 4,
                            ExtraInfo = "Test extra info 4",
                            FirstName = "First4",
                            LastName = "Last4",
                            PaymentType = 0,
                            PersonalCode = 79201748549L
                        },
                        new
                        {
                            ID = 5,
                            ExtraInfo = "Test extra info 5",
                            FirstName = "First5",
                            LastName = "Last5",
                            PaymentType = 0,
                            PersonalCode = 1177739895L
                        },
                        new
                        {
                            ID = 6,
                            ExtraInfo = "Test extra info 6",
                            FirstName = "First6",
                            LastName = "Last6",
                            PaymentType = 1,
                            PersonalCode = 68745945131L
                        },
                        new
                        {
                            ID = 7,
                            ExtraInfo = "Test extra info 7",
                            FirstName = "First7",
                            LastName = "Last7",
                            PaymentType = 1,
                            PersonalCode = 42717135335L
                        },
                        new
                        {
                            ID = 8,
                            ExtraInfo = "Test extra info 8",
                            FirstName = "First8",
                            LastName = "Last8",
                            PaymentType = 1,
                            PersonalCode = 84201775727L
                        },
                        new
                        {
                            ID = 9,
                            ExtraInfo = "Test extra info 9",
                            FirstName = "First9",
                            LastName = "Last9",
                            PaymentType = 1,
                            PersonalCode = 86871840273L
                        },
                        new
                        {
                            ID = 10,
                            ExtraInfo = "Test extra info 10",
                            FirstName = "First10",
                            LastName = "Last10",
                            PaymentType = 0,
                            PersonalCode = 47804328631L
                        });
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.EventCompany", b =>
                {
                    b.HasOne("RIK_Proovitöö.Models.Company", "Company")
                        .WithMany("EventCompanies")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIK_Proovitöö.Models.Event", "Event")
                        .WithMany("EventCompanies")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.EventIndividual", b =>
                {
                    b.HasOne("RIK_Proovitöö.Models.Event", "Event")
                        .WithMany("EventIndividuals")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIK_Proovitöö.Models.Individual", "Individual")
                        .WithMany("EventIndividuals")
                        .HasForeignKey("IndividualID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.Company", b =>
                {
                    b.Navigation("EventCompanies");
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.Event", b =>
                {
                    b.Navigation("EventCompanies");

                    b.Navigation("EventIndividuals");
                });

            modelBuilder.Entity("RIK_Proovitöö.Models.Individual", b =>
                {
                    b.Navigation("EventIndividuals");
                });
#pragma warning restore 612, 618
        }
    }
}
